carnets_admin_carnet_blog_comment:
    resource: "@CarnetsBundle/Resources/config/routing/blogcomment.yml"
    prefix:   /admin/carnet/blog/comment

carnets_admin_carnet_blog_category:
    resource: "@CarnetsBundle/Resources/config/routing/blogcategory.yml"
    prefix:   /admin/carnet/blog/category

carnets_admin_carnet_blog_article:
    resource: "@CarnetsBundle/Resources/config/routing/blogarticle.yml"
    prefix:   /admin/carnet/blog/article

carnets_admin_general_texte:
    resource: "@CarnetsBundle/Resources/config/routing/generaltexte.yml"
    prefix:   /admin/general/texte

carnets_admin_page:
    resource: "@CarnetsBundle/Resources/config/routing/page.yml"
    prefix:   /admin/page

carnets_admin_lieu:
    resource: "@CarnetsBundle/Resources/config/routing/lieu.yml"
    prefix:   /admin/lieu

carnets_admin_carnet:
    resource: "@CarnetsBundle/Resources/config/routing/carnet.yml"
    prefix:   /admin/carnet


#
#     cote front office
#
general_texte_show:
    path:     /{slug}.html
    defaults: { _controller: "CarnetsBundle:GeneralTexte:show" }

carnets_de_voy_homepage:
    path:     /nos-voyages
    defaults: { _controller: CarnetsBundle:Default:index }

carnets_de_voy_destination:
    path:     /carnet/{slug}
    defaults: { _controller: CarnetsBundle:Carnet:show }

carnets_de_voy_ville:
    path:     /carnet/{carnet}/{ville}.html
    defaults: { _controller: CarnetsBundle:Lieu:show }

carnets_de_voy_page:
    path:     /carnet/{carnet}/{ville}/{page}.html
    defaults: { _controller: CarnetsBundle:Page:show }

carnets_de_voy_blog:
    path:     /carnet/le-lounge/
    defaults: { _controller: CarnetsBundle:Default:indexBlog }

carnets_de_voy_blog_article:
    path:     /carnet/le-lounge/{slug}
    defaults: { _controller: CarnetsBundle:BlogArticle:show }

#
#     AJAX
#
carnets_de_voy_twitter:
    path:     /twitter
    defaults: { _controller: CarnetsBundle:Twitter:index }

carnets_de_voy_carte_path:
    path:     /carnet/path/{slug}
    defaults: { _controller: CarnetsBundle:Carnet:path }
