admin_ligne:
    path:     /
    defaults: { _controller: "TclBundle:Ligne:index" }

admin_ligne_new:
    path:     /new
    defaults: { _controller: "TclBundle:Ligne:new" }

admin_ligne_create:
    path:     /create
    defaults: { _controller: "TclBundle:Ligne:create" }
    methods:  POST

admin_ligne_edit:
    path:     /{id}/edit
    defaults: { _controller: "TclBundle:Ligne:edit" }

admin_ligne_update:
    path:     /{id}/update
    defaults: { _controller: "TclBundle:Ligne:update" }
    methods:  [POST, PUT]

admin_ligne_delete:
    path:     /{id}/delete
    defaults: { _controller: "TclBundle:Ligne:delete" }
    methods:  [POST, DELETE,GET]

admin_ligne_favoris:
    path:     /favoris
    defaults: { _controller: "TclBundle:Ligne:index" }