domotique_domobox_homepage:
    path:     /hello/{name}
    defaults: { _controller: DomotiqueDomoboxBundle:Default:index }


# venant des modules
domotiquebundle_domobox_module_flux_json:
    path:     /module/esp8266/post/json/
    defaults: { _controller: "DomotiqueReseauBundle:Log:addJson" }
    methods:  [POST]