# venant des modules
domotiquebundle_domobox_module_flux_json:
    path:     /module/esp8266/post/json/
    defaults: { _controller: "DomotiqueDomoboxBundle:Input:addJson" }
    methods:  [POST]

#donne la moyenne
domotique_log_moyen:
    path: /log/moyenne
    defaults: { _controller: "DomotiqueDomoboxBundle:Output:logMoyenne" }

#retourne l'heure local
domobox_get_hour:
    path: /flux/hour
    defaults: { _controller: "DomotiqueDomoboxBundle:Output:getCurrentDate" }
