language: php

php:
  - 5.5.30
  - 5.6

services:
  - mysql

## Customize dependencies
#dependencies
#  override:
#    - mkdir -p build/logs
#    - composer install --dev --no-interaction
#    - sed -i 's/^;//' ~/.phpenv/versions/$(phpenv global)/etc/conf.d/xdebug.ini


before_script:
  - mysql -e 'create database test;'
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install --no-interaction
  - php app/console doctrine:schema:update --force
  - php app/console fos:user:create test test test --super-admin
  - php app/console doctrine:migrations:migrate -n
  - php app/console cache:clear

script:
#  - phpunit -c app/
#  - phpunit -c app/ --coverage-text --coverage-clover build/logs/coverage.xml -c app

  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

after_script:
#  - travis_retry php /bin/coveralls
#  - bin/coveralls -v --config .coveralls.yml;
#  - bin/coveralls --config .coveralls.yml;
#  - php vendor/satooshi/php-coveralls/bin/coveralls --root_dir build/logs/*.xml
#  - php vendor/satooshi/php-coveralls/bin/coveralls --root_dir app/build/logs/*.xml

notifications:
  email:
    - laurent@llovem.eu