language: php

php:
#  - 5.5
  - 5.6

services:
  - mysql

before_script:
  - mysql -e 'create database test;'
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install --dev
  - php app/console doctrine:schema:update --force
  - php app/console fos:user:create test test test --super-admin
  - php app/console doctrine:migrations:migrate -n
  - php app/console xml:tcl
  - mkdir -p build/logs

script:
  - phpunit -c app/
  - phpunit -c app/ --coverage-text --coverage-clover build/logs/coverage.xml -c app

after_script:
  - cd build/logs/
  - ls l
  - php vendor/bin/coveralls -c .coveralls.yml
#  - bin/coveralls -v --config .coveralls.yml;
#  - bin/coveralls --config .coveralls.yml;
#  - php vendor/satooshi/php-coveralls/bin/coveralls --root_dir build/logs/*.xml
#  - php vendor/satooshi/php-coveralls/bin/coveralls --root_dir app/build/logs/*.xml

notifications:
  email:
    - laurent@llovem.eu