language: php

php:
  - 5.6

services:
  - mysql

before_script:
  - mysql -e 'create database test;'
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install
  - php app/console doctrine:schema:update --force
  - php app/console doctrine:fixtures:load

script: phpunit --coverage-text


notifications:
  email:
    - laurent@llovem.eu