language: php

php:
  - 5.6

before_script:
  - composer install
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - php app/console doctrine:schema:update --force


notifications:
  email:
    - laurent@llovem.eu