language: php

php:
  - 5.5
  - 5.6
  - hhvm

services:
  - mysql

before_script:
  - mysql -e 'create database test;'
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install --dev
  - php app/console doctrine:schema:update --force
  - php app/console fos:user:create test test test --super-admin
  - php app/console doctrine:migrations:migrate -n
  - php app/console xml:tcl
  - mkdir -p build/logs

script:
  - phpunit -c app/
  - phpunit -c app/ --coverage-text --coverage-clover build/logs/clover.xml -c app

after_script:
  ## Coveralls
#  - php bin/coveralls -v

after_success:
#  - coveralls
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php bin/coveralls -v; fi;'


notifications:
  email:
    - laurent@llovem.eu