admin_tcl_ligne:
    resource: "@TclBundle/Resources/config/routing/ligne.yml"
    prefix:   /admin/tcl/ligne

admin_tcl_feed:
    resource: "@TclBundle/Resources/config/routing/feed.yml"
    prefix:   /admin/tcl/feed