tcl_admin_ligne:
    resource: "@TclBundle/Resources/config/routing/ligne.yml"
    prefix:   /admin/ligne

admin_tcl_feed:
    resource: "@TclBundle/Resources/config/routing/feed.yml"
    prefix:   /admin/tcl/feed

tcl_homepage:
    path:     /tcl/home/
    defaults: { _controller: TclBundle:Default:index }
