services:
#    tcl.example:
#        class: TclBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    curling.cool:
        class: TclBundle\Services\CurlCurling
        arguments: ["@service_container"]

    outils.date:
        class: TclBundle\Services\Outils
        arguments: ["@service_container"]

    plip.plop:
        class: CarnetsBundle\Services\Menu