domotiquebundle_front:
    resource: "@DomotiquebundleFrontBundle/Resources/config/routing.yml"
    prefix:   /

commun_to_do:
    resource: "@CommunToDoBundle/Resources/config/routing.yml"
    prefix:   /

domotiquebundle_module:
    resource: "@DomotiquebundleModuleBundle/Resources/config/routing.yml"
    prefix:   /

domotiquebundle_task:
    resource: "@DomotiquebundleTaskBundle/Resources/config/routing.yml"
    prefix:   /


programme_tv:
    resource: "@ProgrammeTvBundle/Resources/config/routing.yml"
    prefix:   /

tcl:
    resource: "@TclBundle/Resources/config/routing.yml"
    prefix:   /

carnets_de_voy:
    resource: "@CarnetsBundle/Resources/config/routing.yml"
    prefix:   /

commun_user:
    resource: "@CommunUserBundle/Controller/"
    type:     annotation
    prefix:   /admin/
    defaults:  { _controller: CommunUserBundle:Admin:index }

user_bundle:
   resource: "@CommunUserBundle/Resources/config/routing.yml"

homepage:
    pattern:   /
    defaults:  { _controller: CommunUserBundle:Home:index }

elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"