domotique_reseau:
    resource: "@DomotiqueReseauBundle/Resources/config/routing.yml"
    prefix:   /

carnet_app_twitter:
    resource: "@CarnetAppTwitterBundle/Resources/config/routing.yml"
    prefix:   /

carnet_app_static_page:
    resource: "@CarnetAppStaticPageBundle/Resources/config/routing.yml"
    prefix:   /

carnet_app_tool:
    resource: "@CarnetAppToolBundle/Resources/config/routing.yml"
    prefix:   /

carnet_app_carnet:
    resource: "@CarnetAppCarnetBundle/Resources/config/routing.yml"
    prefix:   /

carnet_app_blog:
    resource: "@CarnetAppBlogBundle/Resources/config/routing.yml"
    prefix:   /


#domotiquebundle_front:
#    resource: "@DomotiquebundleFrontBundle/Resources/config/routing.yml"
#    prefix:   /

commun_to_do:
    resource: "@CommunToDoBundle/Resources/config/routing.yml"
    prefix:   /

#domotiquebundle_module:
#    resource: "@DomotiquebundleModuleBundle/Resources/config/routing.yml"
#    prefix:   /
#
#domotiquebundle_task:
#    resource: "@DomotiquebundleTaskBundle/Resources/config/routing.yml"
#    prefix:   /


programme_tv:
    resource: "@ProgrammeTvBundle/Resources/config/routing.yml"
    prefix:   /

tcl:
    resource: "@TclBundle/Resources/config/routing.yml"
    prefix:   /

#carnets_de_voy:
#    resource: "@CarnetsBundle/Resources/config/routing.yml"
#    prefix:   /

commun_user:
    resource: "@CommunUserBundle/Controller/"
    type:     annotation
    prefix:   /admin/
    defaults:  { _controller: CommunUserBundle:Admin:index }

user_bundle:
   resource: "@CommunUserBundle/Resources/config/routing.yml"

homepage:
    pattern:   /
    defaults:  { _controller: CommunUserBundle:Home:index }

elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"