Domotique\bundle\ModuleBundle\Entity\SondeUnit:
    type: entity
    table: domotique__sonde_unit
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id
            generator:
                strategy: IDENTITY
    fields:
        symbole:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        nom:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        slug:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: slug
    lifecycleCallbacks: {  }
