Domotique\bundle\ModuleBundle\Entity\SondeType:
    type: entity
    table: domotique__sonde_type
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
    lifecycleCallbacks: {  }
