admin_carnet_blog_comment:
    path:     /
    defaults: { _controller: "CarnetsBundle:BlogComment:index" }

admin_carnet_blog_comment_show:
    path:     /{id}/show
    defaults: { _controller: "CarnetsBundle:BlogComment:show" }

admin_carnet_blog_comment_new:
    path:     /new
    defaults: { _controller: "CarnetsBundle:BlogComment:new" }

admin_carnet_blog_comment_create:
    path:     /create
    defaults: { _controller: "CarnetsBundle:BlogComment:create" }
    methods:  POST

admin_carnet_blog_comment_edit:
    path:     /{id}/edit
    defaults: { _controller: "CarnetsBundle:BlogComment:edit" }

admin_carnet_blog_comment_update:
    path:     /{id}/update
    defaults: { _controller: "CarnetsBundle:BlogComment:update" }
    methods:  [POST, PUT]

admin_carnet_blog_comment_delete:
    path:     /{id}/delete
    defaults: { _controller: "CarnetsBundle:BlogComment:delete" }
    methods:  [POST, DELETE, GET]
