admin_carnet_blog_article:
    path:     /
    defaults: { _controller: "CarnetsBundle:BlogArticle:index" }

admin_carnet_blog_article_show:
    path:     /{slug}/show
    defaults: { _controller: "CarnetsBundle:BlogArticle:show" }

admin_carnet_blog_article_new:
    path:     /new
    defaults: { _controller: "CarnetsBundle:BlogArticle:new" }

admin_carnet_blog_article_create:
    path:     /create
    defaults: { _controller: "CarnetsBundle:BlogArticle:create" }
    methods:  POST

admin_carnet_blog_article_edit:
    path:     /{id}/edit
    defaults: { _controller: "CarnetsBundle:BlogArticle:edit" }

admin_carnet_blog_article_update:
    path:     /{id}/update
    defaults: { _controller: "CarnetsBundle:BlogArticle:update" }
    methods:  [POST, PUT]

admin_carnet_blog_article_delete:
    path:     /{id}/delete
    defaults: { _controller: "CarnetsBundle:BlogArticle:delete" }
    methods:  [POST, DELETE, GET]
