admin_page:
    path:     /
    defaults: { _controller: "CarnetsBundle:Page:index" }

admin_page_show:
    path:     /{id}/show
    defaults: { _controller: "CarnetsBundle:Page:show" }

admin_page_new:
    path:     /new
    defaults: { _controller: "CarnetsBundle:Page:new" }

admin_page_create:
    path:     /create
    defaults: { _controller: "CarnetsBundle:Page:create" }
    methods:  POST

admin_page_edit:
    path:     /{id}/edit
    defaults: { _controller: "CarnetsBundle:Page:edit" }

admin_page_update:
    path:     /{id}/update
    defaults: { _controller: "CarnetsBundle:Page:update" }
    methods:  [POST, PUT]

admin_page_delete:
    path:     /{id}/delete
    defaults: { _controller: "CarnetsBundle:Page:delete" }
    methods:  [POST, DELETE, GET]

admin_page_order:
    path:     /order/edit/
    defaults: { _controller: "CarnetsBundle:Page:order" }
    methods:  [POST, PUT]
