admin_domotique_module_emplacement:
    path:     /
    defaults: { _controller: "DomotiquebundleModuleBundle:Emplacement:index" }

admin_domotique_module_emplacement_show:
    path:     /{id}/show
    defaults: { _controller: "DomotiquebundleModuleBundle:Emplacement:show" }

admin_domotique_module_emplacement_new:
    path:     /new
    defaults: { _controller: "DomotiquebundleModuleBundle:Emplacement:new" }

admin_domotique_module_emplacement_create:
    path:     /create
    defaults: { _controller: "DomotiquebundleModuleBundle:Emplacement:create" }
    methods:  POST

admin_domotique_module_emplacement_edit:
    path:     /{id}/edit
    defaults: { _controller: "DomotiquebundleModuleBundle:Emplacement:edit" }

admin_domotique_module_emplacement_update:
    path:     /{id}/update
    defaults: { _controller: "DomotiquebundleModuleBundle:Emplacement:update" }
    methods:  [POST, PUT]

admin_domotique_module_emplacement_delete:
    path:     /{id}/delete
    defaults: { _controller: "DomotiquebundleModuleBundle:Emplacement:delete" }
    methods:  [POST, DELETE]
