admin_domotique_module_infos:
    path:     /
    defaults: { _controller: "DomotiquebundleModuleBundle:Infos:index" }

admin_domotique_module_infos_show:
    path:     /{id}/show
    defaults: { _controller: "DomotiquebundleModuleBundle:Infos:show" }

admin_domotique_module_infos_new:
    path:     /new
    defaults: { _controller: "DomotiquebundleModuleBundle:Infos:new" }

admin_domotique_module_infos_create:
    path:     /create
    defaults: { _controller: "DomotiquebundleModuleBundle:Infos:create" }
    methods:  POST

admin_domotique_module_infos_edit:
    path:     /{id}/edit
    defaults: { _controller: "DomotiquebundleModuleBundle:Infos:edit" }

admin_domotique_module_infos_update:
    path:     /{id}/update
    defaults: { _controller: "DomotiquebundleModuleBundle:Infos:update" }
    methods:  [POST, PUT]

admin_domotique_module_infos_delete:
    path:     /{id}/delete
    defaults: { _controller: "DomotiquebundleModuleBundle:Infos:delete" }
    methods:  [POST, DELETE]
