admin_domotique_module_logs:
    path:     /
    defaults: { _controller: "DomotiquebundleModuleBundle:Logs:index" }

admin_domotique_module_logs_show:
    path:     /{id}/show
    defaults: { _controller: "DomotiquebundleModuleBundle:Logs:show" }

admin_domotique_module_logs_delete:
    path:     /{id}/delete
    defaults: { _controller: "DomotiquebundleModuleBundle:Logs:delete" }
    methods:  [POST, DELETE, GET]

admin_domotique_module_logs_truncate:
    path:     /truncate
    defaults: { _controller: "DomotiquebundleModuleBundle:Logs:truncate" }
    methods:  [POST, DELETE, GET]


