admin_domotique_module_sonde_unit:
    path:     /
    defaults: { _controller: "DomotiquebundleModuleBundle:SondeUnit:index" }

admin_domotique_module_sonde_unit_show:
    path:     /{id}/show
    defaults: { _controller: "DomotiquebundleModuleBundle:SondeUnit:show" }

admin_domotique_module_sonde_unit_new:
    path:     /new
    defaults: { _controller: "DomotiquebundleModuleBundle:SondeUnit:new" }

admin_domotique_module_sonde_unit_create:
    path:     /create
    defaults: { _controller: "DomotiquebundleModuleBundle:SondeUnit:create" }
    methods:  POST

admin_domotique_module_sonde_unit_edit:
    path:     /{id}/edit
    defaults: { _controller: "DomotiquebundleModuleBundle:SondeUnit:edit" }

admin_domotique_module_sonde_unit_update:
    path:     /{id}/update
    defaults: { _controller: "DomotiquebundleModuleBundle:SondeUnit:update" }
    methods:  [POST, PUT]

admin_domotique_module_sonde_unit_delete:
    path:     /{id}/delete
    defaults: { _controller: "DomotiquebundleModuleBundle:SondeUnit:delete" }
    methods:  [POST, DELETE]
