admin_sensor_type:
    path:     /
    defaults: { _controller: "DomotiqueReseauBundle:SensorType:index" }

admin_sensor_type_show:
    path:     /{id}/show
    defaults: { _controller: "DomotiqueReseauBundle:SensorType:show" }

admin_sensor_type_new:
    path:     /new
    defaults: { _controller: "DomotiqueReseauBundle:SensorType:new" }

admin_sensor_type_create:
    path:     /create
    defaults: { _controller: "DomotiqueReseauBundle:SensorType:create" }
    methods:  POST

admin_sensor_type_edit:
    path:     /{id}/edit
    defaults: { _controller: "DomotiqueReseauBundle:SensorType:edit" }

admin_sensor_type_update:
    path:     /{id}/update
    defaults: { _controller: "DomotiqueReseauBundle:SensorType:update" }
    methods:  [POST, PUT]

admin_sensor_type_delete:
    path:     /{id}/delete
    defaults: { _controller: "DomotiqueReseauBundle:SensorType:delete" }
    methods:  [POST, DELETE]
