admin_sensor_unit:
    path:     /
    defaults: { _controller: "DomotiqueReseauBundle:SensorUnit:index" }

admin_sensor_unit_show:
    path:     /{id}/show
    defaults: { _controller: "DomotiqueReseauBundle:SensorUnit:show" }

admin_sensor_unit_new:
    path:     /new
    defaults: { _controller: "DomotiqueReseauBundle:SensorUnit:new" }

admin_sensor_unit_create:
    path:     /create
    defaults: { _controller: "DomotiqueReseauBundle:SensorUnit:create" }
    methods:  POST

admin_sensor_unit_edit:
    path:     /{id}/edit
    defaults: { _controller: "DomotiqueReseauBundle:SensorUnit:edit" }

admin_sensor_unit_update:
    path:     /{id}/update
    defaults: { _controller: "DomotiqueReseauBundle:SensorUnit:update" }
    methods:  [POST, PUT]

admin_sensor_unit_delete:
    path:     /{id}/delete
    defaults: { _controller: "DomotiqueReseauBundle:SensorUnit:delete" }
    methods:  [POST, DELETE]
