admin_sensor_type:
    path:     /
    defaults: { _controller: "DomotiqueReseauBundle:SondeType:index" }

admin_sensor_type_show:
    path:     /{id}/show
    defaults: { _controller: "DomotiqueReseauBundle:SondeType:show" }

admin_sensor_type_new:
    path:     /new
    defaults: { _controller: "DomotiqueReseauBundle:SondeType:new" }

admin_sensor_type_create:
    path:     /create
    defaults: { _controller: "DomotiqueReseauBundle:SondeType:create" }
    methods:  POST

admin_sensor_type_edit:
    path:     /{id}/edit
    defaults: { _controller: "DomotiqueReseauBundle:SondeType:edit" }

admin_sensor_type_update:
    path:     /{id}/update
    defaults: { _controller: "DomotiqueReseauBundle:SondeType:update" }
    methods:  [POST, PUT]

admin_sensor_type_delete:
    path:     /{id}/delete
    defaults: { _controller: "DomotiqueReseauBundle:SondeType:delete" }
    methods:  [POST, DELETE]
