domotique_reseau_admin_sensor_unit:
    resource: "@DomotiqueReseauBundle/Resources/config/routing/sondeunit.yml"
    prefix:   /admin/sensor/unit

domotique_reseau_admin_sensor_type:
    resource: "@DomotiqueReseauBundle/Resources/config/routing/sondetype.yml"
    prefix:   /admin/sensor/type/

domotique_reseau_admin_module_emplacement:
    resource: "@DomotiqueReseauBundle/Resources/config/routing/emplacement.yml"
    prefix:   /admin/module/emplacement

domotique_reseau_admin_sensor_log:
    resource: "@DomotiqueReseauBundle/Resources/config/routing/log.yml"
    prefix:   /admin/sensor/log