domobox_homepage:
    path:     /domobox/
    defaults: { _controller: DomotiquebundleFrontBundle:Default:index }

#    set une valeur au controleur qui envera au module
domotique_module_set_color:
    path:     /domobox/module/set/
    defaults: { _controller: DomotiquebundleFrontBundle:Default:getModuleColor }

domotique_module_set_curl:
    path:     /domoboxkljsjhkl
    defaults: { _controller: DomotiquebundleFrontBundle:Default:proxy }
