admin_carnet_blog_article:
    path:     /
    defaults: { _controller: "CarnetAppBlogBundle:Article:index" }

admin_carnet_blog_article_show:
    path:     /{slug}/show
    defaults: { _controller: "CarnetAppBlogBundle:Article:show" }

admin_carnet_blog_article_new:
    path:     /new
    defaults: { _controller: "CarnetAppBlogBundle:Article:new" }

admin_carnet_blog_article_create:
    path:     /create
    defaults: { _controller: "CarnetAppBlogBundle:Article:create" }
    methods:  POST

admin_carnet_blog_article_edit:
    path:     /{id}/edit
    defaults: { _controller: "CarnetAppBlogBundle:Article:edit" }

admin_carnet_blog_article_update:
    path:     /{id}/update
    defaults: { _controller: "CarnetAppBlogBundle:Article:update" }
    methods:  [POST, PUT]

admin_carnet_blog_article_delete:
    path:     /{id}/delete
    defaults: { _controller: "CarnetAppBlogBundle:Article:delete" }
    methods:  [POST, DELETE]
